config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :categories
  resources :brands
  resources :blueprints do
    resources :blueprint_translations
    resources :blueprint_values
  end

  resources :expansions
  resources :properties
  resources :voices

  resources :divisions, only: [:index, :new, :edit, :create]

  resources :cats, only: [:index, :new, :edit, :create]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "pages#home"

  get  "dash_user" =>'dashboard#user'
  get  "dash_admin" =>'dashboard#admin'
  get  "dash_superadmin" =>'dashboard#superadmin'
  get  "dashboard" => 'dashboard#index'

  # dashboard pages
  get "user_orders" => 'pages#user_orders'
  get "admin_section" => 'pages#admin_section'
  get "super_section" => 'pages#super_section'



end

app/models/blueprint.rb
class Blueprint < ApplicationRecord
  belongs_to :category
  belongs_to :expansion , optional: true
  belongs_to :brand , optional: true
  has_many :blueprint_values
  has_many :blueprint_details
  has_many :blueprint_translations

  #accepts_nested_attributes_for :blueprint_translations
  accepts_nested_attributes_for :blueprint_translations, :blueprint_values

  #has_many :properties, through: :blueprint_values
  has_one :en_translation, -> { where(locale: "en")} , class_name: "BlueprintTranslation"
  validate :valid_brand?
  has_many :property, through: :blueprint_values
  has_one :rarity, -> { joins(:property).where(properties: { name: 'rarity' }) }, class_name: 'BlueprintValue'

  def valid_brand?
    #se espansionje preseente anche il brand deve sesere presente
    if self.expansion_id.present? && self.brand_id.blank?
      errors.add(:brand_id, "se espansione presente anche il brand deve essere presente")
    end
    #se esp e brand ok allora il brand del blueprint deve essere lo stesso brand dell'espansione alla quale appartiene
    if self.expansion_id.present? && self.brand_id.present? && self.brand_id != self.expansion.brand_id
      errors.add(:brand_id, "se esp e brand ok allora il brand del blueprint deve essere lo stesso brand dell'espansione alla quale appartiene")
    end

  end



end

app/controllers/blueprints_controller.rb
class BlueprintsController < ApplicationController
  before_action :set_blueprint, only: %i[ show update edit destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @blueprints = Blueprint.all.includes(:category, :brand, :expansion, :rarity, :property,    :en_translation , blueprint_values: :property   )

    #@blueprints = Blueprint.includes(blueprint_values: :property).all
  end

  def show
    @blueprint = Blueprint.find(params[:id])
    @blueprint_values = @blueprint.blueprint_values.includes(:property)
    @blueprint_translations = @blueprint.blueprint_translations
  end

  def new
    @blueprint = Blueprint.new
    @blueprint.blueprint_translations.build
    @blueprint.blueprint_values.build

  end

  def edit
  end

  def create
    @blueprint = Blueprint.new(blueprint_params)

    respond_to do |format|
      if @blueprint.save
        format.html { redirect_to blueprints_path, notice: "Blueprint successfully created" }
        format.json { render :show, status: :created, location: @blueprint }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blueprint.errors, status: :unprocessable_entity }
      end
    end

  end

  def update
    respond_to do |format|
      if @blueprint.update(blueprint_params)
        format.html { redirect_to blueprints_url, notice: "Blueprint successfully updated" }
        format.json { render json:, status: :ok, location: @blueprint }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blueprint.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blueprint.destroy!

    respond_to do |format|
      format.html { redirect_to blueprints_url, notice: "Blueprint was successfully destroyed" }
      format.json { head :non_content }
    end
  end

  private

  def set_blueprint
    @blueprint = Blueprint.find(params[:id])
  end

  def blueprint_params
    params.require(:blueprint).permit(
      :id, :category_id, :brand_id, :expansion_id,
      blueprint_translations_attributes: [:id, :name, :locale],
     blueprint_values_attributes: [:id, :property_id, :value]
    )
  end

end

app/helpers/blueprints_helper.rb
module BlueprintsHelper

  def all_categories
    Category.all
  end
  def all_expansions
    Expansion.all
  end


end

app/views/blueprints/_blueprint.html.erb
<div id="<%= dom_id blueprint %>" style="display:grid;grid-template-columns: 110px auto;grid-row: 1 / span 2;">
  <div class="img" style="padding:5px;">
    <%= image_tag "armed.jpg" , style: "width:100px;height:150px" %>
  </div>
  <div>
    <p>
      <strong>Id:</strong>
      <%= blueprint.id %>
    </p>
    <p>
      <strong>Name:</strong>
      <%= blueprint.blueprint_translations.find_by(locale: "en")&.name if blueprint.blueprint_translations %>
    </p>
    <p>
      <strong>Category:</strong>
      <%= blueprint.category.name %>
    </p>

    <p>
      <strong>Brand:</strong>
      <!-- prendo il nome dalla query eseguita all'origine di index nel controller,
       BRAND è OPZIONALE MA collegato ad expansion (se c'è una esxpansion deve esserci il BRAND collegato

       -->
      <%= blueprint.brand.name if blueprint.brand %>
    </p>


    <p>
      <strong>Expansion:</strong>
      <%= blueprint.expansion.name if blueprint.expansion %>
    </p>
    <p>


<hr>
    <p>Values</p>
    <table>

      <tbody>
      <% @blueprint_values.each do |value| %>
        <tr>
          <td><strong><%= value.property.name %></strong></td>
          <td><%= value.value %></td>
          <td><%= link_to "Edit",  edit_blueprint_blueprint_value_path(value.blueprint_id, value.id) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>





    <hr>
    <p><strong>Translation</strong></p>
    <table>
      <tbody>
      <% @blueprint_translations.each do |translation| %>
        <tr>
          <td><%= translation.name %></td>
          <!--<td><%#= translation.description %></td>-->
          <td>| <%= translation.locale %></td>
          <td><%= link_to "Edit",  edit_blueprint_blueprint_translation_path(translation.blueprint_id, translation.id) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  
  </div>
</div>

app/views/blueprints/_form.html.erb
<p> Hello <%= current_user.first_name %> !</p>
<%= form_with(model: blueprint) do |form| %>

  <% if blueprint.errors.any? %>
    <div style="color:#770000">
      <h3><%= pluralize(blueprint.errors.count, "error") %>, prohibited this blueprint from being saved:</h3>

      <ul>
        <%= blueprint.errors.each do |error| %>
          <li><%= error.message %></li>

        <% end %>
      </ul>
    </div>
  <% end %>


  <%#= form.hidden_field :blueprint_id, valUE: @blueprint.id %>

  <div>
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, all_categories, :id, :name, {include_blank: "Select a Category"}%>

  </div>

  <div>
    <%= form.label :brand_id %>
    <%= form.collection_select :brand_id, all_brands, :id, :name , {include_blank: "Select a Brand"}%>
  </div>

  <div>
    <%= form.label :expansion_id %>
    <%= form.collection_select :expansion_id, all_expansions ,:id, :name , {include_blank: "Select an Expansion"}%>
  </div>
  <br><br>

  <p><strong>Blueprint translations fields</strong>  </p>
  <div>



    <%= form.fields_for :blueprint_translations do |translation_form| %>
      
      <div>
        <%= translation_form.label :name %>
        <%= translation_form.text_field :name %>
      </div>

      <div>
        <%= translation_form.label :locale %>
        <%= translation_form.select :locale, options_for_select(['en', 'fr', 'es']) %>
        <!-- Replace options_for_select with your actual locales -->
      </div>
    <% end %>

    <br><br>
      <p><strong> Blueprint values fields </strong></p>
      <div>
        <%= form.fields_for :blueprint_values do |value_form| %>
          <div>
            <%= value_form.label :property_id %>
            <%= value_form.collection_select :property_id, Property.all, :id, :name %>
            <!-- Replace Property.all, :id, :name with your actual data -->
          </div>

          <div>
            <%= value_form.label :value %>
            <%= value_form.text_field :value %>
          </div>
        <% end %>
      </div>

  </div>

  <div>
    <br><br>
    <%= form.submit %>
  </div>

<% end %>

app/views/blueprints/edit.html.erb
<h2>Editing Blueprint</h2>

<%= render "form" , blueprint: @blueprint%>

<br>
<div>
  <%= link_to "Show this blueprint", @blueprint %>
  <%= link_to "back to blueprints", blueprints_path %>
</div>

app/views/blueprints/index.html.erb
<p style="color:green"><%= notice %></p>
<%= link_to "New Blueprint", new_blueprint_path, class: "btn btn-success", style: "float:right;" %>
<h2> Blueprints</h2>
<div id="blueprints" style="display: grid;grid-template-columns: 500px 250px; ">
  <div style="grid-column: 1 / span 2">
    <hr>
  </div>
  <% @blueprints.each do |blueprint| %>
    <div>
      <div id="<%= dom_id blueprint %>" style="display:grid;grid-template-columns: 110px auto;grid-row: 1 / span 2;">
        <div class="img" style="padding:5px;">
          <%= image_tag "armed.jpg", style: "width:100px;height:150px" %>
        </div>
        <div>
          <p>
            <strong>Id:</strong>
            <%= blueprint.id %>
          </p>
          <p>
            <strong>Name:</strong>
            <%= blueprint.en_translation&.name if blueprint.en_translation %>

          </p>
          <p>
            <strong>Category:</strong>
            <%= blueprint.category.name %>
          </p>

          <p>
            <strong>Brand:</strong>
            <!-- prendo il nome dalla query eseguita all'origine di index nel controller,
             BRAND è OPZIONALE MA collegato ad expansion (se c'è una esxpansion deve esserci il BRAND collegato

             -->
            <%= blueprint.brand.name if blueprint.brand %>
          </p>


          <p>
            <strong>Expansion:</strong>
            <%= blueprint.expansion.name if blueprint.expansion %>
          </p>




          <% if blueprint.blueprint_values.any? %>

            <% blueprint.blueprint_values.each do |blueprint_value| %>
              <% if blueprint_value.property.name != 'rarity'  %>
              <p>
                <strong style="text-transform: capitalize;"><%= blueprint_value.property.name %>:</strong>
                <%= blueprint_value.value %>
              </p>
                <% end %>
            <% end %>

          <% else %>
            <p>No blueprint values available for this blueprint.</p>
          <% end %>



<% if  blueprint.rarity&.value? %>

          <p style="color:red"><strong>Rarity:</strong> <%= blueprint.rarity&.value %></p>
<% end %>

        </div>
      </div>
    </div>
    <div style="display:flex;align-items: center;justify-content: center">
      <%= link_to "show this blueprint", blueprint, class: "btn btn-primary" %>
    </div>
    <div style="grid-column: 1 / span 2">
      <hr>
    </div>
  <% end %>
</div>


app/views/blueprints/new.html.erb
<h2>New Blueprint</h2>

<p> Hello <%= current_user.first_name %> !</p>
<%= render "form", blueprint: @blueprint %>
<br>
<div>
  <%= link_to "back to blueprints", blueprints_path %>
</div>

app/views/blueprints/show.html.erb

<div id="show_blueprints"  style="display: grid;grid-template-columns: 500px 250px;  grid-auto-rows: 36px !important;">
  <div>
    <%= render @blueprint %>
  </div>
<div style="display: grid;row-gap:3px;">
  <%= link_to "back to blueprint", blueprints_path , class: "btn btn-primary"%>
  <br>
  <%= link_to "edit this blueprint", edit_blueprint_path(@blueprint) , class: "btn btn-secondary"%>

  <%= link_to "New_translation", new_blueprint_blueprint_translation_path(:blueprint_id => @blueprint.id) , class: "btn btn-secondary"%>


  <%= link_to "New Value", new_blueprint_blueprint_value_path(:blueprint_id => @blueprint.id) , class: "btn btn-secondary"%>

<br>
   <%= button_to("destroy this blueprint",  @blueprint,  method: :delete,  data: { turbo_method: 'delete', turbo_confirm: 'Really Destroy?' } , class: "btn btn-danger" , style: "width:100%" ) %>

</div>
</div>