config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :categories
  resources :brands
  resources :blueprints do
    resources :blueprint_translations
    resources :blueprint_values
  end

  resources :expansions
  resources :properties
  resources :voices

  resources :divisions, only: [:index, :new, :edit, :create]

  resources :cats, only: [:index, :new, :edit, :create]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "pages#home"

  get  "dash_user" =>'dashboard#user'
  get  "dash_admin" =>'dashboard#admin'
  get  "dash_superadmin" =>'dashboard#superadmin'
  get  "dashboard" => 'dashboard#index'

  # dashboard pages
  get "user_orders" => 'pages#user_orders'
  get "admin_section" => 'pages#admin_section'
  get "super_section" => 'pages#super_section'



end

app/models/blueprint_value.rb
class BlueprintValue < ApplicationRecord

  belongs_to :property
  accepts_nested_attributes_for :property, reject_if: :all_blank#, allow_destroy: true

  belongs_to :blueprint
=begin
  self.table_name = 'blueprint_values_view'
=end
  validates :value , presence: true
end

app/controllers/blueprint_values_controller.rb
class BlueprintValuesController < ApplicationController
  before_action :set_blueprint
  before_action :set_blueprint_value, only: %i[ show edit update destroy]
  before_action :authenticate_user!, except: [:index, :show]


  def show
  end

  def new
    @blueprint_value = BlueprintValue.new
  end

  def edit
  end

  def create
    @blueprint_value = BlueprintValue.new(blueprint_value_params)

    respond_to do |format|
      if @blueprint_value.save
        format.html { redirect_to blueprint_path(@blueprint), notice: "Blueprint Value successfully created" }
        format.json { render json: @blueprint_value, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blueprint_value.errors, status: :unprocessable_entity }
      end
    end

  end

  def update
    respond_to do |format|
      if @blueprint_value.update(blueprint_value_params)
        format.html { redirect_to blueprint_path(@blueprint), notice: "Blueprint Value successfully updated" }
        format.json { render json: @blueprint_value, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blueprint_value.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  end

  private

  def set_blueprint
    @blueprint = Blueprint.find(params[:blueprint_id])
  end



  def set_blueprint_value
    @blueprint_value = BlueprintValue.find(params[:id])
  end

  def blueprint_value_params
    params.require(:blueprint_value).permit(:value, :blueprint_id, :property_id)
  end
end

app/helpers/blueprint_values_helper.rb
module BlueprintValuesHelper

  def all_properties
    Property.all
  end


end

app/views/blueprint_values/_blueprint_values.html.erb
<div id= "<%= dom_id blueprint_value %>">
  <p>
    <%= form.text_field :blueprint_id, value: @blueprint.id %>
    <strong>id:</strong>
    <%= blueprint_value.id %>
  </p>
  <p>
    <strong>Category:</strong>
    <%=  blueprint_translation.name%>

  </p>

  <p>
    <strong>Brand:</strong>
    <!-- prendo il nome dalla query eseguita all'origine di index nel controller,
     BRAND è OPZIONALE MA collegato ad expansion (se c'è una esxpansion deve esserci il BRAND collegato

     -->
    <%= blueprint_translation.blueprint.blueprint_id if blueprint_translation.blueprint %>
  </p>


  <p>
    <strong>Expansion:</strong>
    <%= blueprint.expansion.name if blueprint.expansion %>
  </p>


</div>

app/views/blueprint_values/_form.html.erb
<p> Hello <%= current_user.first_name %> !</p>

<%= form_with(model: [@blueprint, @blueprint_value]) do |form| %>

  <% if blueprint_value.errors.any? %>
    <div style="color:#770000">
      <h3><%= pluralize(blueprint_value.errors.count, "error") %>, prohibited this blueprint value from being saved:</h3>

      <ul>
        <%= blueprint_value.errors.each do |error| %>
          <li><%= error.message %></li>

        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :blueprint_id, value: @blueprint.id %>
  <div>
    <div>
      <%= form.collection_select(:property_id, all_properties, :id, :name, { prompt: "Seleziona una Property" }, class: "form-control") %>

    </div>

    <%= form.label :'Inserisci il valore', style: "display: block" %>
    <%= form.text_field :value %>
  </div>

  <%= form.submit  %>
<% end %>

app/views/blueprint_values/edit.html.erb
<h2>Edit Blueprint values</h2>


<%= render "form" , blueprint_value: @blueprint_value%>

<br>
<div>

  <%= link_to "back to blueprints", blueprint_url(@blueprint) %>

</div>

app/views/blueprint_values/index.html.erb
<p style="color: green"><%= notice %></p>

<h2>Blueprint values</h2>


app/views/blueprint_values/new.html.erb
<h2>New Blueprint Value</h2>

<%= render "form", blueprint_value: @blueprint_value %>
<br>
<div>
  <%= link_to "back to blueprints", blueprints_path %>
</div>