config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :categories
  resources :brands
  resources :blueprints do
    resources :blueprint_translations
    resources :blueprint_values
  end

  resources :expansions
  resources :properties
  resources :voices

  resources :divisions, only: [:index, :new, :edit, :create]

  resources :cats, only: [:index, :new, :edit, :create]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "pages#home"

  get  "dash_user" =>'dashboard#user'
  get  "dash_admin" =>'dashboard#admin'
  get  "dash_superadmin" =>'dashboard#superadmin'
  get  "dashboard" => 'dashboard#index'

  # dashboard pages
  get "user_orders" => 'pages#user_orders'
  get "admin_section" => 'pages#admin_section'
  get "super_section" => 'pages#super_section'



end

app/models/property.rb
class Property < ApplicationRecord
  has_many :blueprint_values
  has_many :blueprints, through: :blueprint_values

  validates :name , presence: true, uniqueness: true
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  #before_action :set_blueprint_value
  before_action :set_property, only: %i[ show edit update destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @properties = Property.all
  end
  def show
  end
  def new
    @property = Property.new
  end
  def edit
  end
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to properties_url, notice: "Property was succesfully created."}
        format.json { render :show, status: :created, location: @property}
      else
        format.html { render :new, status: :unprocessable_entity}
        format.json { render json: @property.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to properties_url, notice: "Property was succesfully updated!"}
        format.json { render :show, status: ok, location: @property}
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @property.destroy!

    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was succesfully destroyed"}
      format.json { head :no_content}
    end
  end

  private
  def set_blueprint_value
    @blueprint_value = BlueprintValue.find(params[:id])
  end
  def set_property
    @property = Property.find(params[:id])
  end

  def property_params
    params.require(:property).permit(:name)
  end

end

app/helpers/properties_helper.rb
module PropertiesHelper
  def all_types
    ["text", "longtext", "numeric", "currency", "email", "telephone"]
  end

  def all_types_for_select
    all_types.map{ | l | [l, l] }
  end
end

app/helpers/properties_helpers.rb
module PropertiesHelper
  def all_types
    ["text", "longtext", "numeric", "currency", "email", "telephone"]
  end

  def all_types_for_select
    all_types.map{ | l | [l, l] }
  end
end

app/views/properties/_form.html.erb
<p> Ciao <%= current_user.first_name %>!</p>

<%= form_with(model: property) do |f| %>
  <% if property.errors.any? %>
  <div style="color:#770000">
    <h3><%= pluralize(property.errors.count, "error") %> prohibited this game from being saved:</h3>
    <ul>
      <% property.errors.each do |error| %>
      <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div>
    <%= f.label :Name, style: "display: block" %>
    <%= f.text_field :name %>
  </div>


<div>
  <%= f.submit %>
</div>


<% end %>

app/views/properties/_property.html.erb
<div id="<%= dom_id property %>">
  <p><strong>Name:</strong><%= property.name %></p>
  <p><strong>Id:</strong><%= property.id %></p>
</div>

app/views/properties/edit.html.erb
<h2>editing Proeprty</h2>
<%= render "form", property: @property %>
<br>
<div>
  <%= link_to "Show this property", @property %>
  <%= link_to "back to Properties", properties_path %>
</div>

app/views/properties/index.html.erb
<p style="color:green"><%= notice %></p>

<h2>Properties</h2>
<div id="proprties">
  <% @properties.each do |property| %>
    <%= render property %>
  <p> <%= link_to "Show this property", property  %></p>
  <% end %>
</div>

<%= link_to "New property", new_property_path %>

app/views/properties/new.html.erb
<h2>New Property</h2>

<%= render "form", property: @property %>
<br>
<div>
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/show.html.erb
<p style="color:green"><%= notice %></p>

<%= render @property %>
<div>
  <%= link_to "Edit this property", edit_property_path %>
  <%= link_to "Back to properties", properties_path %>

  <%= button_to("destroy this property",  @property,  method: :delete,  data: { turbo_method: 'delete', turbo_confirm: 'Really Destroy?' }   ) %>
</div>