config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :categories
  resources :brands
  resources :blueprints do
    resources :blueprint_translations
    resources :blueprint_values
  end

  resources :expansions
  resources :properties
  resources :voices

  resources :divisions, only: [:index, :new, :edit, :create]

  resources :cats, only: [:index, :new, :edit, :create]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "pages#home"

  get  "dash_user" =>'dashboard#user'
  get  "dash_admin" =>'dashboard#admin'
  get  "dash_superadmin" =>'dashboard#superadmin'
  get  "dashboard" => 'dashboard#index'

  # dashboard pages
  get "user_orders" => 'pages#user_orders'
  get "admin_section" => 'pages#admin_section'
  get "super_section" => 'pages#super_section'



end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blueprint.rb
class Blueprint < ApplicationRecord
  belongs_to :category
  belongs_to :expansion , optional: true
  belongs_to :brand , optional: true
  has_many :blueprint_values
  has_many :blueprint_details
  has_many :blueprint_translations

  #accepts_nested_attributes_for :blueprint_translations
  accepts_nested_attributes_for :blueprint_translations, :blueprint_values

  #has_many :properties, through: :blueprint_values
  has_one :en_translation, -> { where(locale: "en")} , class_name: "BlueprintTranslation"
  validate :valid_brand?
  has_many :property, through: :blueprint_values
  has_one :rarity, -> { joins(:property).where(properties: { name: 'rarity' }) }, class_name: 'BlueprintValue'

  def valid_brand?
    #se espansionje preseente anche il brand deve sesere presente
    if self.expansion_id.present? && self.brand_id.blank?
      errors.add(:brand_id, "se espansione presente anche il brand deve essere presente")
    end
    #se esp e brand ok allora il brand del blueprint deve essere lo stesso brand dell'espansione alla quale appartiene
    if self.expansion_id.present? && self.brand_id.present? && self.brand_id != self.expansion.brand_id
      errors.add(:brand_id, "se esp e brand ok allora il brand del blueprint deve essere lo stesso brand dell'espansione alla quale appartiene")
    end

  end



end

app/models/blueprint_value.rb
class BlueprintValue < ApplicationRecord

  belongs_to :property
  accepts_nested_attributes_for :property, reject_if: :all_blank#, allow_destroy: true

  belongs_to :blueprint
=begin
  self.table_name = 'blueprint_values_view'
=end
  validates :value , presence: true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :blueprints
  validates :name, presence: true, uniqueness: true
end

app/models/cat.rb
class Cat < ApplicationRecord
  belongs_to :parent, class_name: 'Cat', optional: true
  has_many :children, class_name: 'Cat', foreign_key: 'parent_id', dependent: :destroy

  validates :name, presence: true

  scope :root_cats, -> { where(parent_id: nil) }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :blueprints

  validates :name, presence: true, uniqueness: true



end

app/models/division.rb
class Division < ApplicationRecord

  has_many :children, class_name: 'Division', foreign_key: 'parent_id'
  belongs_to :parent, class_name: 'Division', optional: true
  has_many :voices

  accepts_nested_attributes_for :voices

  has_one :eng_translation, -> { where(locale: "en")} , class_name: "Voice"

end

app/models/expansion.rb
class Expansion < ApplicationRecord
  belongs_to :brand
  has_many :blueprints

  validates :name, presence: true
  validates :name, :uniqueness => {scope: :brand}
end

app/models/property.rb
class Property < ApplicationRecord
  has_many :blueprint_values
  has_many :blueprints, through: :blueprint_values

  validates :name , presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :confirmable, :recoverable, :rememberable, :validatable, :trackable

  validates :role, presence: true
  enum role: %w[superadmin admin moderator user].index_by(&:itself), _prefix: :role
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role
    self.role ||= "user"

  end
=begin

  def is_superadmin?
    self.current_user.role == "superadmin"
  end
  def is_admin?
    self.current_user.role == "admin"
  end
=end




end

app/models/voice.rb
class Voice < ApplicationRecord

  belongs_to :division

  validates :name, presence: true
  validates :locale, presence: true


end

app/controllers/voices_controller.rb
class VoicesController < ApplicationController
  before_action :set_voice, only: [:edit, :update, :destroy]

  def index
    @voices = Voice.all
  end

  def new
    @voice = Voice.new
  end

  def create
    @voice = Voice.new(voice_params)
    if @voice.save
      redirect_to voices_path, notice: 'Voice was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @voice.update(voice_params)
      redirect_to voices_path, notice: 'Voice was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @voice.destroy
    redirect_to voices_path, notice: 'Voice was successfully destroyed.'
  end

  private

  def set_voice
    @voice = Voice.find(params[:id])
  end

  def voice_params
    params.require(:voice).permit(:name, :division_id, :locale)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/blueprints_helper.rb
module BlueprintsHelper

  def all_categories
    Category.all
  end
  def all_expansions
    Expansion.all
  end


end

app/helpers/brands_helper.rb
module BrandsHelper

  def all_brands
    Brand.all
  end

end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/helpers/locales_helper.rb
module LocalesHelper
  def all_locales
    ["en", "it", "fr", "de"]
  end

  def all_locales_for_select
    all_locales.map{ | l | [l, l] }
  end
end

app/helpers/pages_helper.rb
module PagesHelper



end

app/helpers/properties_helper.rb
module PropertiesHelper
  def all_types
    ["text", "longtext", "numeric", "currency", "email", "telephone"]
  end

  def all_types_for_select
    all_types.map{ | l | [l, l] }
  end
end

app/helpers/properties_helpers.rb
module PropertiesHelper
  def all_types
    ["text", "longtext", "numeric", "currency", "email", "telephone"]
  end

  def all_types_for_select
    all_types.map{ | l | [l, l] }
  end
end

app/helpers/voices_helper.rb
module VoicesHelper
  def all_localex
    ["en", "it", "fr", "de"]
  end


end

app/views/voices/_form.html.erb
<%= form_with(model: division || voice, local: true) do |form| %>
  <% if division&.errors&.any? || voice&.errors&.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(division&.errors&.count || voice&.errors&.count, "error") %> prohibited this <%= division ? 'division' : 'voice' %> from being saved:</h2>

      <ul>
        <% (division&.errors&.full_messages || voice&.errors&.full_messages).each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <% if division %>
    <!-- Division-specific form fields -->
    <div class="field">
      <%= form.label :parent_id %>
      <%= form.collection_select :parent_id, Division.all, :id, :id, { prompt: 'Select Parent (Optional)' } %>
    </div>
  <% elsif voice %>
    <!-- Voice-specific form fields -->
    <div class="field">
      <%= form.label :division_id %>
      <%= form.collection_select :division_id, Division.all, :id, :id, { prompt: 'Select Division' } %>
    </div>

    <div class="field">
      <%= form.label :locale %>
      <%= form.text_field :locale, value: 'en' %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/voices/edit.html.erb
<h1>Edit Voice</h1>

<%= render 'form' ,[division: @division , voice: @voice] %>

<%= link_to 'Back', voices_path %>

app/views/voices/index.html.erb
<h1>Voices</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Division ID</th>
    <th>Locale</th>
    <th colspan="3"></th>
  </tr>

  <% @voices.each do |voice| %>
    <tr>
      <td><%= voice.id %></td>
      <td><%= voice.name %></td>
      <td><%= voice.division_id %></td>
      <td><%= voice.locale %></td>
      <td><%= link_to 'Show', voice %></td>
      <td><%= link_to 'Edit', edit_voice_path(voice) %></td>
      <td><%= link_to 'Destroy', voice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<br>
<p>ciao</p>



<%= link_to 'New Voice', new_voice_path %>

app/views/voices/new.html.erb
<h1>New Voice</h1>

<%= render 'form' ,[division: @division , voice: @voice] %>

<%= link_to 'Back', voices_path %>